//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CircusWPF.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actor
    {
        public int Id { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> QuantityEvent { get; set; }
    
        public virtual Statuses Statuses { get; set; }
    }
}
