//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CircusWPF.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animals()
        {
            this.ScheduleTrainings = new HashSet<ScheduleTrainings>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> IdGender { get; set; }
        public Nullable<int> Weight { get; set; }
        public string FoodDesc { get; set; }
        public string CareDesc { get; set; }
        public Nullable<int> IdTrainer { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleTrainings> ScheduleTrainings { get; set; }
    }
}
