//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CircusWPF.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleEvent
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> IdEvent { get; set; }
        public Nullable<int> IdEmployee { get; set; }
        public Nullable<int> IdPromoter { get; set; }
        public Nullable<int> IdPromoType { get; set; }
        public Nullable<decimal> Prepayment { get; set; }
        public Nullable<decimal> Expenses { get; set; }
        public Nullable<decimal> TicketsProfit { get; set; }
        public Nullable<decimal> Profit { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Promoter Promoter { get; set; }
        public virtual PromoTypes PromoTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
